### ISSUE TITLE
Missing Composer.json file + add to packagist.

### ISSUE THREAD

**Issue by dambrogia** [gudTECH/retailops_magento2#1]
It would be awesome if this project had a composer.json file to allow for autoloading through composer. I would be happy to make a PR to add this in.

The icing on top would but if this was added to packagist so users of this API didn't have to declare an extra repository in their composer.json and had a one step install. 👍

**Comment by dnorman** [comment]
Thank you @dambrogia for the offer. We would be happy to accept such pull requests.

Please note that while we do reserve the right to curate this repository, it comes with absolutely no official support or warranty. The code within this repository is fundamentally a community-maintained project, by and for the RetailOps partner and customer community. 

We do officially support the SDK interactions which it uses however, available at: https://github.com/gudtech/retailops-sdk 

We welcome whatever contributions you see fit to add here, and wish you good luck on your project!
